version: '2.1'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=kevin123
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
